version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password